background0 = "#2e3440"
background1 = "#3b4252"
background2 = "#434c5e"
background3 = "#4c566a"
foreground0 = "#eceff4"
foreground1 = "#e5e9f0"
foreground2 = "#d8dee9"
accent0 = "#8fbcbb"
accent1 = "#88c0d0"
accent2 = "#81a1c1"
accent3 = "#5e81ac"
red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
