bg0 = "#2e3440"
bg1 = "#3b4252"
bg2 = "#434c5e"
bg3 = "#4c566a"
fg0 = "#eceff4"
fg1 = "#e5e9f0"
fg2 = "#d8dee9"
accent0 = "#8fbcbb"
accent1 = "#88c0d0"
accent2 = "#81a1c1"
accent3 = "#5e81ac"
red = "#bf616a"
orange = "#d08770"
yellow = "#ebcb8b"
green = "#a3be8c"
purple = "#b48ead"
